1.18.0-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/filter/braille/drivers/index/textbrftoindexv3.in b/filter/braille/drivers/index/textbrftoindexv3.in
--- a/filter/braille/drivers/index/textbrftoindexv3.in
+++ b/filter/braille/drivers/index/textbrftoindexv3.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2017 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -57,10 +57,35 @@ then
   else
     cat "$FILE"
   fi | (
-    while read LINE
+    while IFS=$'\n' read -r LINE
     do
       # Strip CRs
       LINE=${LINE//$'\015'}
+      # Ignore SUBs
+      LINE=${LINE//$'\032'}
+
+      # Interpret FFs
+      while [ -n "$LINE" -a -z "${LINE/#$'\014'*}" ]
+      do
+        printf "\\f"
+	LINE=${LINE#$'\014'}
+      done
+
+      # Make sure there is nothing else we don't process
+      if [ -n "$LINE" ]
+      then
+	if [ -z "${LINE/*[$'\001'-$'\037'$'\177']*}" ]
+	then
+	  echo "ERROR: unsupported control character in BRF file" >&2
+	  exit 1
+	fi
+	if [ -z "${LINE/*[$'\200'-$'\377']*}" ]
+	then
+	  echo "ERROR: unsupported non-ASCII character in BRF file" >&2
+	  exit 1
+	fi
+      fi
+
       CHARS=$(printf %s "$LINE" | wc -c)
       if [ "$CHARS" -gt 127 ]
       then
